### ISSUE TITLE
sync with new SBT version

### ISSUE THREAD

**Issue by kliegr** [propi/rdfrules#32]
It seems that SBT is not compatible with jdk 13 and 14.
https://github.com/sbt/sbt/issues/5509 ("We don't test sbt on JDK 14, so that could also be the problem. Please run it on JDK 8 or 11.")
If this is true, the documentation should warn about this. 
For me, it works with JDK 11.

Also, the `run-main` command on  RDFRules homepage does not seem to work with current version of SBT - https://github.com/clulab/eidos/issues/440.
It seems it was replaceed by `runMain`.

**Comment by propi** [comment]
Now in the doc `run-main` was replaced with `runMain`
