### ISSUE TITLE
instantiation of "body" and "head" return unexpected results

### ISSUE THREAD

**Issue by kliegr** [propi/rdfrules#34]
The instantiation of "body" and "head" seem to return the same result as the instantiation of the whole rule.

**Comment by propi** [comment]
Originally, for example: "head" instantiates only head and projects constants into the body based on the same variables. The condion was that the instatiated body must exist in the KG.

Now the strategy was changed. If you specify "body", it instantiates the body and projects constants to the head, but the head need not exist in the KG. The same behavior for the "head".
