### ISSUE TITLE
Deserialization exception - Invalid type of measure

### ISSUE THREAD

**Issue by kliegr** [propi/rdfrules#38]
If json-serialized rules contain confidence or some other measure, they cannot be deserialized via Load ruleset due to  Deserialization exception - Invalid type of measure. 

rules.json
`[
  {
    "body": [
      {
        "object": {
          "type": "variable",
          "value": "?a"
        },
        "predicate": "<interacts_with>",
        "subject": {
          "type": "variable",
          "value": "?b"
        }
      }
    ],
    "head": {
      "object": {
        "type": "variable",
        "value": "?b"
      },
      "predicate": "<interacts_with>",
      "subject": {
        "type": "variable",
        "value": "?a"
      }
    },
    "measures": [
      {
        "name": "BodySize",
        "value": 11702212
      },
      {
        "name": "HeadCoverage",
        "value": 0.9917442958647477
      },
      {
        "name": "Support",
        "value": 11605602
      },
      {
        "name": "HeadSize",
        "value": 11702212
      },
      {
        "name": "Confidence",
        "value": 0.9917442958647477
      }
    ]
  }
]
`

**Comment by propi** [comment]
It works for me in version 1.4+. Please attach the whole json task with a sample of input data.

**Comment by kliegr** [comment]
It looks like this is triggered if you put "Compute PCA Confidence" as the next node. 
Load Index -> Load Rule Set> Compute PCA Confidence > Get rules.

Will attach data if this is not enough.

**Comment by kliegr** [comment]
Now I tested again on a different machine and it seems to work.. maybe some UI issue.

**Comment by kliegr** [comment]
I have tracked it down.
If "Load Rules" is the first node in the pipeline and it is set to load a JSON file, "Rules format" does not have to be specified and the file loads ok.

If "Load Ruleset" is used after "Load Index", and "Rules format" is left blank, it throws the deserialization exception. If "Rules format" is set to "JSON" the file loads ok.

**Comment by propi** [comment]
> If "Load Ruleset" is used after "Load Index", and "Rules format" is left blank, it throws the deserialization exception. If "Rules format" is set to "JSON" the file loads ok.

It is normal behaviour. "Load Ruleset" default format is "Cache".

**Comment by kliegr** [comment]
In this case, the system should give correct error message. Error "Invalid type of measure" is misleading.

**Comment by kliegr** [comment]
Someone may also see it as counterintuitive to have different defaults for effectively the same operator in different contexts.

**Comment by propi** [comment]
Ok, it should be cleared and fixed.

**Comment by propi** [comment]
Fixed in 1.6.0
