### ISSUE TITLE
Constraints application

### ISSUE THREAD

**Issue by janasim** [propi/rdfrules#52]
When running a task in an example, choosing a rule from the output and trying to search it in another run by applying the constraints in the mining task, the rule is not found.
The top-k is set but I guess that it should not affect the constraints application.
Example: 
[constrait_issue.zip](https://github.com/propi/rdfrules/files/5298126/constrait_issue.zip)

**Comment by propi** [comment]
This is a problem with patterns which must also be connected like rules. The pattern is: 
`( ? ? <P53597> ) => ( ? <object> [<P0DTC2>,<P0DTC2-PRO..0000449647>,<P0DTC2-PRO..0000449648>,<P0DTC2-PRO..0000449649>] )`
The mining process starts refining the head. It replaces ? with the variable ?a. But the rule must be connected; therefore the next atom of the body must contain variable ?a. The pattern `( ? ? <P53597> )` is replaced by an atom `( ?a p <P53597> )`. Unfortunately there is no support in data for this rule: `( ?a p <P53597> ) => ( ?a <object> C )`. We need `( ?b ? <P53597> ) ^ ( ?a ? ?b ) => ( ?a <object> ? )`.

This problem may be included in future work: **How to get rid of sequential patterns which are dependent on gradual refining**.

**Comment by kliegr** [comment]
I am not entirely sure this is the right reason. As far as I recall, the same task without the <object> head predicate constraint ran fine and returned results including a particular rule with <object> as a predicate in the head. When  <object> head predicate constraint is added to the task,  the same rule is not found.

**Comment by propi** [comment]
> I am not entirely sure this is the right reason. As far as I recall, the same task without the head predicate constraint ran fine and returned results including a particular rule with as a predicate in the head. When head predicate constraint is added to the task, the same rule is not found.

Are you able to replicate it with a small dataset on which I can test it? It is really strange behavior.

**Comment by kliegr** [comment]
At this point, the task settings for reproduction are available only for the large "indexNew2" index :( (in the attachment to the original report). But the server is free.

**Comment by propi** [comment]
"Orderless" option added into patterns where atoms ordering does not matter.
