### ISSUE TITLE
Support of a rule differs from the number of instances

### ISSUE THREAD

**Issue by janasim** [propi/rdfrules#56]
Support of a rule differs from the number of its instances and the sparl query result
[molecular_interacts.zip](https://github.com/propi/rdfrules/files/5424338/molecular_interacts.zip)

**Comment by propi** [comment]
RDFRules disables duplicate instantiated atoms in the rule. Some instantiated head can have connected only such instantiated body which contains distinct instantiated atoms. Duplicate atoms are prohibited and therefore the support is decreased.

For example: ( ?a <molecularl..racts_with> <P08913> ) ^ ( <DrugCentral_621> <molecularl..racts_with> ?b ) => ( ?a <molecularl..racts_with> ?b ) | HeadCoverage: 0.18402877697841727, HeadSize: 13900, Confidence: 0.22403222981257664, BodySize: 11418, Support: 2558

If ?a in the head is instantiated as DrugCentral_621 and ?b is anything then we obtained two identical instantiated atoms in the rule, so this instantiation is skipped and support is decreased.

Duplicates checking is used only during mining - probably not in the instantiation task in the postprocessing phase.
