### ISSUE TITLE
Conflicting documentation of measures

### ISSUE THREAD

**Issue by kliegr** [propi/rdfrules#64]
Currently, the GitHub documentation states that

HeadSize is 

    "The head size of a rule is a measure which indicates a number of triples (or instances) conforming the head of the rule."

However, in the [paper](http://www.semantic-web-journal.net/system/files/swj_3.) it is defined as 

    "the number of triples from the KG having the same predicate that occurs in the rule head". 

If the head atom contains a constant at one of the positions, then these definitions are not equivalent.

**Comment by propi** [comment]
Fixed
